### ISSUE TITLE
Support for multiline text

### ISSUE THREAD

**Issue by ir-fuel** [kuznetsovVladislav/KVSpinnerView#1]
Sorry, no pull request.

in `RectangleLayer.swift` : 

```
            let messageWidth = messageString.size(attributes: [NSFontAttributeName : font]).width
            let messageHeight = messageString.size(attributes: [NSFontAttributeName : font]).height
            path = bezierPathWithStatus(width: messageWidth).cgPath
            let statusLayer = StatusTitleLayer(message: message, 				//TODO: - Perhapse need to extend font in settings
                                               frame: CGRect(
                                                x: messageWidth > rectSide ? -rectSide : 0,
                                                y: 0.0,
                                                width: messageWidth > rectSide ? messageWidth : rectSide,
                                                height: max(25,messageHeight)))

```

I added `messageHeight` and changed the `height` param in the rectangle frame

**Comment by kuznetsovVladislav** [comment]
Tnx for feedback, fixed this issue.  Check it out!

**Comment by kuznetsovVladislav** [comment]
Also you are able to create pull requests by forking my repo.
https://gist.github.com/Chaser324/ce0505fbed06b947d962

**Comment by ir-fuel** [comment]
Yes I know, I just took a local copy because I needed to change some more things for my project :)

FYI this change isn't 100% correct I noticed. Somewhere in your code you still have a "30" hardcoded for the height of the text part. Don't remember anymore where it was however.

**Comment by ir-fuel** [comment]
It only influences the vertical centering of the view if I remember correctly. So it won't take the 2nd line into account when calculating the vertical position. Not really a big deal.
